from . import bubble_sort
from . import insertion_sort
from . import selection_sort
from . import merge_sort
from . import bubble_sort_of_doom
from . import cocktail_sort_of_doom
from . import py_timsort
from . import quick_sort
from . import heap_sort
from . import bogo_sort
from . import bogo_sort_of_doom
from . import shell_sort
from . import comb_sort